#ifndef FIRST_DEFAULTS_H_
#define FIRST_DEFAULTS_H_

#include "_first_all.h"

boolean DEFAULT_STRINGS_LENGTH_TRIM;
boolean DEFAULT_STRINGS_OK_TRIM;
boolean DEFAULT_STRINGS_EQUAL_NORMALISE;
boolean DEFAULT_STRINGS_INDEX_OF_NORMALISE;
boolean DEFAULT_STRINGS_MATCHES_NORMALISE;
boolean DEFAULT_STRINGS_SPLIT_NORMALISE;
size_t DEFAULT_ARRAYS_ITEM_SIZE;
boolean DEFAULT_ERROR_WARNING_OK_PROPERTIES;
boolean DEFAULT_OUTPUT_OK_PROPERTIES;

char* DEFAULT_SEPARATOR;
char* DEFAULT_SEPARATOR_ITEMS;
char* DEFAULT_ENCLOSURE_EXTERNAL_START;
char* DEFAULT_ENCLOSURE_EXTERNAL_END;
char* DEFAULT_ENCLOSURE_INTERNAL_START;
char* DEFAULT_ENCLOSURE_INTERNAL_END;

#endif
