#ifndef FIRST_DEFAULTS_H_
#define FIRST_DEFAULTS_H_

#include "_first_all.h"

boolean DEFAULT_STRINGS_LENGTH_TRIM;
boolean DEFAULT_STRINGS_OK_TRIM;
boolean DEFAULT_STRINGS_EQUAL_NORMALISE;
boolean DEFAULT_STRINGS_INDEX_OF_NORMALISE;
boolean DEFAULT_STRINGS_MATCHES_NORMALISE;
boolean DEFAULT_STRINGS_SPLIT_NORMALISE;
size_t DEFAULT_ARRAYS_ITEM_LENGTH;

char* DEFAULT_SEPARATOR;
char* DEFAULT_SEPARATOR_START;
char* DEFAULT_SEPARATOR_END;
char* DEFAULT_SEPARATOR_ITEMS;

#endif
