#include "headers/_first_defaults.h"

boolean DEFAULT_STRINGS_LENGTH_TRIM = TRUE;
boolean DEFAULT_STRINGS_OK_TRIM = TRUE;
boolean DEFAULT_STRINGS_EQUAL_NORMALISE = TRUE;
boolean DEFAULT_STRINGS_INDEX_OF_NORMALISE = TRUE;
boolean DEFAULT_STRINGS_MATCHES_NORMALISE = TRUE;
boolean DEFAULT_STRINGS_SPLIT_NORMALISE = TRUE;
size_t DEFAULT_ARRAYS_ITEM_LENGTH = 1000;

char* DEFAULT_SEPARATOR = " --- ";
char* DEFAULT_SEPARATOR_ITEMS = ", ";
char* DEFAULT_ENCLOSURE_EXTERNAL_START = "{ ";
char* DEFAULT_ENCLOSURE_EXTERNAL_END = " }";
char* DEFAULT_ENCLOSURE_INTERNAL_START = "(";
char* DEFAULT_ENCLOSURE_INTERNAL_END = ")";
