#include "headers/_first_defaults.h"

boolean DEFAULT_STRINGS_LENGTH_TRIM = FALSE;
boolean DEFAULT_STRINGS_OK_TRIM = TRUE;
boolean DEFAULT_STRINGS_EQUAL_NORMALISE = TRUE;
boolean DEFAULT_STRINGS_INDEX_OF_NORMALISE = TRUE;
boolean DEFAULT_STRINGS_MATCHES_NORMALISE = TRUE;
boolean DEFAULT_STRINGS_SPLIT_NORMALISE = TRUE;
boolean DEFAULT_STRINGS_CONTAINS_NORMALISE = TRUE;

size_t DEFAULT_ARRAYS_ITEM_SIZE = 1000;
boolean DEFAULT_ERROR_WARNING_OK_PROPERTIES = TRUE;
boolean DEFAULT_OUTPUT_OK_PROPERTIES = TRUE;
size_t DEFAULT_IO_FILE_TOT_LINES = 100;
size_t DEFAULT_IO_FILE_LINE_SIZE = 1000;
size_t DEFAULT_IO_NAME_SIZE = 100;
boolean DEFAULT_IO_PATH_IS_ABSOLUTE = TRUE;

char* DEFAULT_SEPARATOR = " --- ";
char* DEFAULT_SEPARATOR_ITEMS = ", ";
char* DEFAULT_ENCLOSURE_EXTERNAL_START = "{ ";
char* DEFAULT_ENCLOSURE_EXTERNAL_END = " }";
char* DEFAULT_ENCLOSURE_INTERNAL_START = "(";
char* DEFAULT_ENCLOSURE_INTERNAL_END = ")";
